version: "3.9"
services:
  django:
    container_name: ride_rank
    build: .
    command: >
      sh -c "
        python manage.py makemigrations || echo 'No migrations to make';
        until python manage.py migrate; do
          echo 'Waiting for database...'
          sleep 5
        done
        python manage.py loaddata /app/initial_data.json || echo 'Data already loaded'
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
    ports:
      - "8000:8000"
